### ISSUE TITLE
Build fails with Go 1.13

### ISSUE THREAD

**Issue by willamowius** [psanford/tpm-fido#19]
"go build" failed on Ubuntu 20.04 with the installed Go 1.13. It seems you need at least 1.16. You should mention this in the Readme. Go 1.20 worked fine.

**Comment by psanford** [comment]
The go.mod file specifies the language compatible min version.  Our policy is to only support N and N-1 versions of Go where N is the currently released major version. I would accept a PR to update the readme to state this policy.

**Comment by willamowius** [comment]
Sorry, I'm new to Go. The first error was "undefined: ecdsa.SignASN1" and I missed the error mesage about 1.16 after that.
