### ISSUE TITLE
Add support for TPM 1.2

### ISSUE THREAD

**Issue by darkdragon-001** [psanford/tpm-fido#2]
Google also provides a library for TPM 1.2, so it should be easy to implement this as well. Would be nice, if I could also get this to work in my old laptop.

There are several ways to [termine TPM version](https://newbedev.com/how-to-determine-if-computer-has-tpm-trusted-platform-module-available).

**Comment by psanford** [comment]
Currently tpm-fido uses the CTAP1 protocol. CTAP1 requires ECC algorithms, which are not supported by TPM 1.2. 

I believe that CTAP2+FIDO2 does have support for RSA, although I'm not aware of any actual implementations that are using RSA.

If someone has the appetite to add support for TPM 1.2, you'd probably need to start by adding protocol support for CTAP2.
