### ISSUE TITLE
add package for Debian/Ubuntu?

### ISSUE THREAD

**Issue by monperrus** [psanford/tpm-fido#21]
@psanford this repo is excellent, many thanks for it.

Since it's critical, what about packaging it in popular distros such as Debian or Ubuntu?

**Comment by psanford** [comment]
Having this packaged and included in distros is up to the distro maintainers, not me. I would encourage you to go through the packaging process with your distribution of choice.

**Comment by monperrus** [comment]
Ack. For the record, one first ping is https://answers.launchpad.net/ubuntu/+source/tpm2-tools/+question/707062
