### ISSUE TITLE
Use TPM counter

### ISSUE THREAD

**Issue by darkdragon-001** [psanford/tpm-fido#3]
According to [this article](https://blog.hansenpartnership.com/webauthn-in-linux-with-a-tpm-via-the-hid-gadget/), all TPMs should offer a NV counter. Looking through the golang library, I found [`NVIncrement()`](https://github.com/google/go-tpm/blob/master/tpm2/tpm2.go#L1180-L1187).

**Comment by psanford** [comment]
While this is something we could do, I don't think there's any practical benefit. The point of the counter is to allow RPs to detect a cloned key. In practice no RPs check for this (maybe Google does?). But if a RP really want to, the current implementation of using a timestamp is sufficient. I suppose there is a small risk of having your system clock off, but again in practice RPs don't check this value.
