### ISSUE TITLE
Unable to use this when logging in to okta

### ISSUE THREAD

**Issue by asdil12** [psanford/tpm-fido#9]
I'm using the chromium based browser vivaldi and try to add this token to okta. But it doesn't seem to work and only this log appears:

All that is happening on a thinkpad T14s.

```
2022/09/26 10:32:59 unsuppoted cmd: CmdCbor 16
2022/09/26 10:32:59 got AuthenticateCmd site=<unknown 5f3f121c11812e9b5e76652f4df0325e732baacce8fdc8485036857918ea1826>
2022/09/26 10:32:59 invalid key: invalid key handle (key handle size: 65)
2022/09/26 10:32:59 got AuthenticateCmd site=<unknown 5f3f121c11812e9b5e76652f4df0325e732baacce8fdc8485036857918ea1826>
2022/09/26 10:32:59 invalid key: invalid key handle (key handle size: 64)
2022/09/26 10:32:59 got AuthenticateCmd site=<unknown 5f3f121c11812e9b5e76652f4df0325e732baacce8fdc8485036857918ea1826>
2022/09/26 10:32:59 invalid key: invalid key handle (key handle size: 96)
2022/09/26 10:32:59 got RegisterCmd site=<unknown 5f3f121c11812e9b5e76652f4df0325e732baacce8fdc8485036857918ea1826>

**Comment by psanford** [comment]
Hmm, I was able to enroll tpm-fido with an okta account (in chrome). I've not tested with Vivaldi at all. Does it work with other sites from Vivaldi? You should be able to test with https://webauthn.io/

If it is working with other sites then it might be a specific configuration enabled on your org's okta account. Can you share the details of the fido2 configuration for your org? It is possible that your organization is limiting registration to specific fido attestation certificates. If that is the case then you'll need to ask your org admin to update the policy to allow for the tpm-fido attestation cert.

**Comment by asdil12** [comment]
I tried webauthn.io but it is the same issue regarding the browser waiting for the usb token:

```
2022/09/26 23:57:04 got VersionCmd
2022/09/26 23:57:13 unsuppoted cmd: CmdCbor 16
2022/09/26 23:57:13 got RegisterCmd site=<unknown 4141414141414141414141414141414141414141414141414141414141414141>
```

I tried vivaldi, chromium and chrome - on openSUSE.
I also tried firefox which only produced:
```
2022/09/26 23:55:42 got VersionCmd
```

**Comment by psanford** [comment]
The logs you've shared look normal. Are you seeing the modal dialog popup saying: `TPM-FIDO` `FIDO Confirm Auth`?

**Comment by psanford** [comment]
It looks like webauthn.io updated their code recently. Now I need to unselect `Require user Verification` in the `Advanced Settings` to allow me to register `tpm-fido` (we should at some point at support for UV).

**Comment by asdil12** [comment]
I don't see the modal dialog.
When I uncheck that "require user verification" flag, the log looks like this:
```
2022/09/27 00:09:16 unsuppoted cmd: CmdCbor 16
2022/09/27 00:09:16 got RegisterCmd site=webauthn.io
```

But it also still doesn't work.
And still no modal dialog.

**Comment by asdil12** [comment]
Ah - I think I found the issue:
While I have `pinentry` installed, I needed to install something like `pinentry-qt5`.

**Comment by asdil12** [comment]
It really was the missing pinentry-qt5. Now I can even login to okta.
I guess that the default console pinentry was opened in the background but the output was not printed anywhere.

**Comment by psanford** [comment]
Yes we do expect a gui pinentry to be present on the system.

I think we could improve this experience. Instead of looking for `pinentry` we can look for the pinentry gui programs:
- pinentry-gtk2
- pinentry-gnome3
- pinentry-qt
- ???

We could still fallback to plain `pinentry` if we don't find any of the gui alternatives, but then we would log a warning message.

**Comment by asdil12** [comment]
Falling back or logging a warning would be a good idea. In this case it really makes sense to use a gui pinentry as this tool can run in the background as a systemd user service (which is how I just configured it on my system)

**Comment by psanford** [comment]
I've added a basic check and warning for this. Thanks for the bug report!
